remove RenderCore dependency on Litho via screenshot library
Summary:
```
buck build fblite
```
fails with error:
```
Failed to execute isolated step <kotlinc>
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/ContentPreAllocator.kt:21:28: error: unresolved reference: mutableObjectIntMapOf
import androidx.collection.mutableObjectIntMapOf
                           ^
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/ContentPreAllocator.kt:48:38: error: unresolved reference: mutableObjectIntMapOf
  private val preAllocationCounter = mutableObjectIntMapOf<String>()
                                     ^
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/ContentPreAllocator.kt:102:28: error: unresolved reference: mutableObjectIntMapOf
    val componentCounter = mutableObjectIntMapOf<String>()
                           ^
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/LithoViewAttributesExtension.kt:30:28: error: unresolved reference: MutableScatterMap
import androidx.collection.MutableScatterMap
                           ^
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/LithoViewAttributesExtension.kt:132:31: error: unresolved reference: MutableScatterMap
    private val currentUnits: MutableScatterMap<Long, ViewAttributes> = MutableScatterMap()
                              ^
fbandroid/libraries/components/litho-core/src/main/java/com/facebook/litho/LithoViewAttributesExtension.kt:132:73: error: unresolved reference: MutableScatterMap
    private val currentUnits: MutableScatterMap<Long, ViewAttributes> = MutableScatterMap()
```

The diff fixes that by removing the Litho dependency which is only meant to be used in tests and debug builds, and not letting it into the app build.

Reviewed By: astreet

Differential Revision: D59533870

fbshipit-source-id: 55472f43d6e84a82915467820e8179fea976ead6